/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Add new preset": "添加新预设",
    "Affects: Crystalliser\n": "影响：结晶器\n",
    "After creating a new preset, you can rename the new preset to something more sensible by clicking on its title.": "创建新预设后，您可以通过单击其标题将新预设重命名为更合理的名称。",
    "Anyone who doesn't comply with the rule will be arrested, and possibly killed.": "任何不遵守规则的人都会被逮捕，甚至可能被杀害。",
    "Basic resources are rationed and reserved for the army.": "基本资源是配给并保留给军队的。",
    "Blank-nomargin": "空白无边距",
    "Crystalliser": "结晶器",
    "Earth": "土",
    "Earth Trickle": "土细流",
    "Everything is in a state of chaos and disorder. There are mass demonstrations everywhere.": "一切都处于混乱无序的状态。 到处都有大规模示威活动。",
    "Free": "免费",
    "I am a button!": "我是一个按钮！",
    "Load": "加载",
    "Lore": "知识",
    "Machine states to save in new preset:": "机器状态保存在新预设中：",
    "My country has recently been invaded and taken control of by oppressive militarist rule.": "我们最近遭到军国主义压迫统治的入侵和控制。",
    "Next upgrade:": "下次升级：",
    "Nothing": "无",
    "Origin": "起源",
    "Origins": "起源",
    "Presets": "预设",
    "PRESETS": "预设",
    "Presets are a way to save machine settings, so you can load them later\n\t\t\twithout having to manually toggle them yourself.": "预设是保存机器设置的一种方式，因此您可以稍后加载它们，而无需自己手动切换。",
    "Production": "生产",
    "The first Alterhistorian": "第一个另类历史学家",
    "The only weakness of the militarists is their lack of knowledge on elemental sciences. They have not limited access to books\n\t\t\ton the subject. I wonder if I can nab a few from the library...": "军国主义者唯一的弱点是缺乏基本科学知识。 他们对与该主题相关的书籍的访问不受限制。 我想知道我是否可以从图书馆借一些...",
    "Then, choose all the machines you want to save in the preset. This makes loading the preset affect those machines and those machines only.\n\t\t\tIn the above example, choose \"Crystalliser.\"": "然后，选择要保存在预设中的所有机器。 这使得加载预设会影响这些机器并且仅影响这些机器。\n\t\t\t在上面的示例中，选择“结晶器”。",
    "To create a new preset, set all machine settings to the one you want to save in the preset.\n\t\t\t(For example, if you want to turn off the first process that produces Earth from nothing in a preset, go turn that off first.)": "要创建新预设，请将所有机器设置设置为您要保存在预设中的设置。\n\t\t\t（例如，如果您要关闭预设中从无到有生成土的第一个进程 ，先把它关掉。）",
    "Upgrades": "升级",
    "I found a rusty old crystallising machine in the basement, and I've\n\t\t\tmanaged to start making some earth by putting a bunch of rocks inside the machine and allowing more to crystalise on it. It's pretty slow though...": "我在地下室发现了一台生锈的旧结晶器，我已经成功地开始制造一些泥土，方法是将一堆岩石放入机器内，并让更多的岩石在上面结晶。 虽然速度相当慢...",
    "The First": "第一",
    "(Info)": "(信息)",
    "No processes use Earth.": "没有进程使用 土。",
    "Preset saved.": "预设已保存。",
    "Usages": "使用情况",
    "Air": "气",
    "Evaporator": "蒸发器",
    "I'm not sure what I'm doing wrong though.\n\t\t\tIf the texts are correct, it should be able to produce water on its own, but the best I can do is force it to turn earth into water.": "不过我不确定我做错了什么。\n\t\t\t如果文本是正确的，它应该能够自己生产水，但我能做的最好的就是强迫它把地球变成 水。",
    "I've uncovered a liquefying machine in the basement.": "我在地下室发现了一台液化机。",
    "Liquefier": "液化器",
    "Lossful Water Conversion": "有损水转化",
    "No processes produce Air.": "没有过程产生气。",
    "No processes use Air.": "没有进程使用 气。",
    "No processes use Water.": "没有过程使用水。",
    "The Second": "第二",
    "Trickle": "细流",
    "Water": "水",
    "Lossful Air Conversion": "有损 气转化",
    "Fire": "火",
    "Forced Conversion": "强制转换",
    "Incinerator": "焚烧炉",
    "Lossful Fire Conversion": "有损火转换",
    "Stream": "蒸汽",
    "No processes use Fire.": "没有进程使用 火。",
    "I still can't figure out what's wrong with my liquefier and my pressure chamber though.": "但我仍然不明白我的液化器和压力室出了什么问题。",
    "It looks like there's a slot on each machine which can be filled with the next element to make it more efficient.": "看起来每台机器上都有一个插槽，可以填充下一个元素以提高效率。",
    "Simple Earth Conversion": "简单的地球转换",
    "The Fifth": "第五",
    "The missing piece to the liquefier was fire all along. \n\t\t\tBy putting some fire into another small slot on the side, I've managed to stumble upon a way to synthesize elements from nothing.": "液化器缺失的部分一直是火。 \n\t\t\t通过在侧面的另一个小槽中放一些火，我成功地找到了一种从无到有合成元素的方法。",
    "Universal Reagent": "通用试剂",
    "With it, my earth and water production is looking good.": "有了它，我的土地和水生产看起来都很好。",
    "With some alchemical magic I can get fire to increase earth gain as well.": "通过一些炼金术魔法，我也可以得到火来增加土增益。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'Ø': 'Ø',
    'v0.2': 'v0.2',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Water ": "水 ",
    "Fire ": "火 ",
    "Air ": "气 ",
    "Earth ": "土 ",
    "Origin ": "起源 ",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Reach (.+) undefined to unlock \(You have (.+) undefined\)$/, '达到 $1 个未定义即可解锁（您有 $2 未定义）'],
    [/^\t(.+)\n\t\t\t\t\tAir\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t气/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tFire\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t火/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tWater\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t水/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEarth\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Fire$/, '$1 火'],
    [/^([\d\.,]+) Air$/, '$1 气'],
    [/^([\d\.,]+) Water$/, '$1 水'],
    [/^([\d\.,]+) Earth$/, '$1 土'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);