/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Add new preset": "添加新预设",
    "Affects: Crystalliser\n": "影响：结晶器\n",
    "After creating a new preset, you can rename the new preset to something more sensible by clicking on its title.": "创建新预设后，您可以通过单击其标题将新预设重命名为更合理的名称。",
    "Anyone who doesn't comply with the rule will be arrested, and possibly killed.": "任何不遵守规则的人都会被逮捕，甚至可能被杀害。",
    "Basic resources are rationed and reserved for the army.": "基本资源是配给并保留给军队的。",
    "Blank-nomargin": "空白无边距",
    "Crystalliser": "结晶器",
    "Earth": "土",
    "Earth Trickle": "土细流",
    "Everything is in a state of chaos and disorder. There are mass demonstrations everywhere.": "一切都处于混乱无序的状态。 到处都有大规模示威活动。",
    "Free": "免费",
    "I am a button!": "我是一个按钮！",
    "Load": "加载",
    "Lore": "知识",
    "Machine states to save in new preset:": "机器状态保存在新预设中：",
    "My country has recently been invaded and taken control of by oppressive militarist rule.": "我们最近遭到军G压迫统治的入侵和控制。",
    "Next upgrade:": "下次升级：",
    "Nothing": "无",
    "Origin": "起源",
    "Origins": "起源",
    "Presets": "预设",
    "PRESETS": "预设",
    "Presets are a way to save machine settings, so you can load them later\n\t\t\twithout having to manually toggle them yourself.": "预设是保存机器设置的一种方式，因此您可以稍后加载它们，而无需自己手动切换。",
    "Production": "生产",
    "The first Alterhistorian": "第一个另类历史学家",
    "The only weakness of the militarists is their lack of knowledge on elemental sciences. They have not limited access to books\n\t\t\ton the subject. I wonder if I can nab a few from the library...": "军G主义者唯一的弱点是缺乏基本科学知识。 他们对与该主题相关的书籍的访问不受限制。 我想知道我是否可以从图书馆借一些...",
    "Then, choose all the machines you want to save in the preset. This makes loading the preset affect those machines and those machines only.\n\t\t\tIn the above example, choose \"Crystalliser.\"": "然后，选择要保存在预设中的所有机器。 这使得加载预设会影响这些机器并且仅影响这些机器。\n\t\t\t在上面的示例中，选择“结晶器”。",
    "To create a new preset, set all machine settings to the one you want to save in the preset.\n\t\t\t(For example, if you want to turn off the first process that produces Earth from nothing in a preset, go turn that off first.)": "要创建新预设，请将所有机器设置设置为您要保存在预设中的设置。\n\t\t\t（例如，如果您要关闭预设中从无到有生成土的第一个进程 ，先把它关掉。）",
    "Upgrades": "升级",
    "I found a rusty old crystallising machine in the basement, and I've\n\t\t\tmanaged to start making some earth by putting a bunch of rocks inside the machine and allowing more to crystalise on it. It's pretty slow though...": "我在地下室发现了一台生锈的旧结晶器，我已经成功地开始制造一些泥土，方法是将一堆岩石放入机器内，并让更多的岩石在上面结晶。 虽然速度相当慢...",
    "The First": "第一",
    "(Info)": "(信息)",
    "No processes use Earth.": "没有进程使用 土。",
    "Preset saved.": "预设已保存。",
    "Usages": "使用情况",
    "Air": "气",
    "Evaporator": "蒸发器",
    "I'm not sure what I'm doing wrong though.\n\t\t\tIf the texts are correct, it should be able to produce water on its own, but the best I can do is force it to turn earth into water.": "不过我不确定我做错了什么。\n\t\t\t如果文本是正确的，它应该能够自己生产水，但我能做的最好的就是强迫它把土变成 水。",
    "I've uncovered a liquefying machine in the basement.": "我在地下室发现了一台液化机。",
    "Liquefier": "液化器",
    "Lossful Water Conversion": "有损水转化",
    "No processes produce Air.": "没有过程产生气。",
    "No processes use Air.": "没有进程使用 气。",
    "No processes use Water.": "没有过程使用水。",
    "The Second": "第二",
    "Trickle": "细流",
    "Water": "水",
    "Lossful Air Conversion": "有损 气转化",
    "Fire": "火",
    "Forced Conversion": "强制转换",
    "Incinerator": "焚烧炉",
    "Lossful Fire Conversion": "有损火转换",
    "Stream": "蒸汽",
    "No processes use Fire.": "没有进程使用 火。",
    "I still can't figure out what's wrong with my liquefier and my pressure chamber though.": "但我仍然不明白我的液化器和压力室出了什么问题。",
    "It looks like there's a slot on each machine which can be filled with the next element to make it more efficient.": "看起来每台机器上都有一个插槽，可以填充下一个元素以提高效率。",
    "Simple Air Conversion": "简单的气转换",
    "Simple Water Conversion": "简单的水转换",
    "Simple Fire Conversion": "简单的火转换",
    "Simple Earth Conversion": "简单的土转换",
    "The Fifth": "第五",
    "The missing piece to the liquefier was fire all along. \n\t\t\tBy putting some fire into another small slot on the side, I've managed to stumble upon a way to synthesize elements from nothing.": "液化器缺失的部分一直是火。 \n\t\t\t通过在侧面的另一个小槽中放一些火，我成功地找到了一种从无到有合成元素的方法。",
    "Universal Reagent": "通用试剂",
    "With it, my earth and water production is looking good.": "有了它，我的土地和水生产看起来都很好。",
    "With some alchemical magic I can get fire to increase earth gain as well.": "通过一些炼金术魔法，我也可以得到火来增加土增益。",
    "Crystalliser, Evaporator\n": "结晶器、蒸发器\n",
    "Crystalliser, Evaporator, Incinerator\n": "结晶器、蒸发器、焚烧炉\n",
    "Crystalliser, Incinerator\n": "结晶器、焚烧炉\n",
    "Crystalliser, Liquefier\n": "结晶器、液化器\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator\n": "结晶器、液化器、蒸发器、焚烧炉\n",
    "Evaporator\n": "蒸发器\n",
    "Evaporator, Incinerator\n": "蒸发器、焚烧炉\n",
    "Incinerator\n": "焚化炉\n",
    "Liquefier\n": "液化器\n",
    "Liquefier, Evaporator, Incinerator\n": "液化器、蒸发器、焚烧炉\n",
    "Crystalliser\n": "结晶器\n",
    "Crystalliser, Liquefier, Evaporator\n": "结晶器、液化器、蒸发器\n",
    "Crystalliser, Liquefier, Incinerator\n": "结晶器、液化器、焚烧炉\n",
    "Liquefier, Evaporator\n": "液化器、蒸发器\n",
    "Liquefier, Incinerator\n": "液化器、焚烧炉\n",
    "Emblemic Power": "纹章力量",
    "Emblems": "纹章",
    "Infuser": "注入器",
    "No processes produce Air Emblems.": "没有任何进程会产生气纹章。",
    "No processes produce Earth Emblems.": "没有任何进程会产生土纹章。",
    "No processes produce Emblemic Power.": "没有任何进程会产生纹章力量。",
    "No processes produce Fire Emblems.": "没有进程会产生火焰纹章。",
    "No processes use Air Emblems.": "没有进程使用气纹章。",
    "No processes use Earth Emblems.": "没有进程使用土纹章。",
    "No processes use Emblemic Power.": "没有进程使用纹章力量。",
    "No processes use Fire Emblems.": "没有进程使用火纹章。",
    "No processes use Water Emblems.": "没有进程使用水纹章。",
    "Orb Infusion": "宝珠注入",
    "But the crystals are gone, possibly damaged during the invasion or sold for other possessions in a desperate attempt to not go hungry. All I've managed to make using them\n\t\t\tare these dense cores of elements that emit a weird glow which hasn't been documented. I'll call them emblems.": "但水晶不见了，可能是在入侵期间受损，或者是为了不挨饿而拼命卖掉其他财产。 我使用它们所做的一切都是这些密集的元素核心，它们发出一种尚未被记录的奇怪光芒。 我将称它们为纹章。",
    "Also, I've noticed something- the texts report that reaction rate is proportional to the amount of reactant, but they always\n\t\t\tseem to stay constant regardless of the amount of reactant I have. I wonder why.": "另外，我还注意到一些事情——文本报告反应速率与反应物的量成正比，但无论我有多少反应物，它们总是\n\t\t\t似乎保持不变。 我想知道为什么。",
    "The texts say that by using compressors with the crystal of the respective element inside them, you can create golems.": "文本中说，通过使用压缩器及其内部相应元素的晶体，您可以创建傀儡。",
    "These past few days have been a success. I found some old elemental compressors from the secret black market I discovered and I have enough elements to fill them.": "这几天很成功。 我从我发现的秘密黑市找到了一些旧的元素压缩机，并且我有足够的元素来填充它们。",
    "Avalanche": "崩塌",
    "Crystalliser, Evaporator, Infuser\n": "结晶器、蒸发器、浸泡器\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser\n": "结晶器、液化器、蒸发器、焚烧器、注入器\n",
    "Crystalliser, Liquefier, Evaporator, Infuser\n": "结晶器、液化器、蒸发器、注入器\n",
    "Crystalliser, Liquefier, Incinerator, Infuser\n": "结晶器、液化器、焚化器、注入器\n",
    "Evaporator, Incinerator, Infuser\n": "蒸发器、焚烧炉、注入器\n",
    "Evaporator, Infuser\n": "蒸发器、注入器\n",
    "Incinerator, Infuser\n": "焚化炉、注入器\n",
    "Liquefier, Incinerator, Infuser\n": "液化器、焚化器、注入器\n",
    "But owing to a special property of the emblems, I can fuse them together using a specialised fusing machine to make secondary elements.": "但由于纹章的特殊性质，我可以使用专门的熔合机将它们熔合在一起，制成次级元件。",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Swamp\n": "结晶器、液化器、蒸发器、焚烧炉、注入器、沼泽\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Swamp, Refrigerator\n": "结晶器、液化器、蒸发器、焚烧炉、注入器、沼泽、冰箱\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Swamp, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、沼泽、冰箱、纹章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Swamp, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化炉、沼泽、冰箱、纹章合并\n",
    "Crystalliser, Liquefier, Evaporator, Swamp, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、沼泽、冰箱、纹章合并\n",
    "Crystalliser, Liquefier, Swamp, Refrigerator, Emblem Merger\n": "结晶器、液化器、沼泽、冰箱、纹章合并\n",
    "Crystalliser, Swamp, Refrigerator, Emblem Merger\n": "结晶器、沼泽、冰箱、纹章合并\n",
    "Emblem Merger": "纹章合并",
    "I thought it should've been possible to make secondary elements just by directly mixing the primary elements, but how wrong I was.": "我认为应该可以通过直接混合主要元素来制作次要元素，但我错了。",
    "Ice": "冰",
    "Traces of Ice": "冰之痕迹",
    "Traces of Mud": "泥之痕迹",
    "Merger": "合并",
    "Mud": "泥",
    "Refrigerator": "制冷机",
    "Secondary": "次要",
    "Secondary (II)": "次要（II）",
    "Swamp": "沼泽",
    "Swamp, Refrigerator, Emblem Merger\n": "沼泽、冰箱、纹章合并\n",
    "The best I can do is force a reaction which converts all elements involved into just one element.": "我能做的最好的事情就是强制一种反应，将所有涉及的元素转化为一个元素。",
    "The primary elements by themselves are immiscible with each other and strongly repel each other when an attempt is made to mix them.": "主要元素本身彼此不混溶，并且当试图将它们混合时彼此强烈排斥。",
    "Assimilation": "同化",
    "There's a particularly interesting element in this text, which the author has named void. It is not described anywhere else, but according to my calculations it should exist.\n\t\t\tThe process of creating void involves smashing magma and steam together, which produces a trace amount of void and some mud- Wait, doesn't that mean void is a convoluted form of air + fire?": "这篇文章中有一个特别有趣的元素，作者将其命名为 void。 其他地方没有描述过，但根据我的计算，它应该存在。 \n\t\t\t创造虚空的过程涉及岩浆和蒸汽一起粉碎，从而产生微量的虚空和一些泥土——等等，不' 这意味着虚空是空气+火的复杂形式吗？",
    "Meanwhile, there's the much more versatile element conversions. Unfortunately, they're horribly inefficient at the start, and there haven't been many\n\t\t\tattempts made to generalise the conversion process, so I'll have to figure out the formulae on my own. But combined with the forceful assimilation of primary elements,\n\t\t\tthey should be enough to catalyse a more complicated process of producing the primary elements.": "同时，还有更通用的元素转换。 不幸的是，它们一开始效率非常低，并且没有进行很多\n\t\t\t尝试来推广转换过程，所以我必须自己找出公式。 但与初级元素的强力同化结合起来，\n\t\t\t它们应该足以催化更复杂的初级元素产生过程。",
    "The secondary elements have some weird property that allows them to absorb the two primary elements they were made up of,\n\t\t\tconverting them into the secondary element. After a bit of reading, I've found good documentation on this process. It still seems to be rather\n\t\t\tinefficient, and no documentation exists on upgrading them.": "次要元素有一些奇怪的属性，允许它们吸收组成它们的两个主要元素，\n\t\t\t将它们转换为次要元素。 经过一番阅读后，我发现了有关此过程的良好文档。 它似乎仍然相当高效，并且没有关于升级它们的文档。",
    "In turn, I can use elements to upgrade the merger to produce more secondary elements. Pretty neat, though I'd really like to get away from the\n\t\t\tinefficient process of emblem merging. It uses way too much primary elements in exchange for just a tiny bit of secondary elements.": "反过来，我可以利用元素进行升级合并，产生更多的次级元素。 非常整洁，尽管我真的很想摆脱\n\t\t\tin高效的徽章合并过程。 它使用了太多的主要元素来换取少量的次要元素。",
    "(MAXED)": "（最大）",
    "Assimilation": "同化",
    "Boiler": "锅炉",
    "Endless Abyss": "无尽深渊",
    "Forced Ice Conversion": "强制冰转换",
    "Forced Magma Conversion": "强制岩浆转换",
    "Forced Mud Conversion": "强制泥浆转换",
    "Forced Sand Conversion": "强制砂型转换",
    "Forced Steam Conversion": "强制蒸汽转换",
    "I'll have to do some digging.": "我得做一些挖掘工作。",
    "I've also noticed that there's no air+fire merge. All the books I can find on elemental sciences have had that part redacted or ripped out. I've tried merging them myself but nothing happened.": "我还注意到没有空气+火合并。 我能找到的所有关于元素科学的书籍都已编辑或删除了该部分。 我尝试过自己合并它们，但什么也没发生。",
    "Magma": "岩浆",
    "Mutualism": "互利共生",
    "No processes use Ice.": "没有进程使用 冰。",
    "No processes use Magma.": "没有进程使用 岩浆。",
    "No processes use Mud.": "没有进程使用 泥。",
    "People say they come biweekly. I was lucky they didn't discover my laboratory, but I'll have to start relocating my laboratory to a more secluded space.": "人们说他们每两周来一次。 我很幸运他们没有发现我的实验室，但我必须开始将我的实验室搬到一个更僻静的地方。",
    "Pulverizer": "粉碎机",
    "Sand": "沙",
    "Secondary II": "次要 II",
    "So it turns out I can use two secondary elements to upgrade the conversion speed of the similar element they represent.": "所以事实证明我可以使用两个辅助元素来提升它们所代表的相似元素的转换速度。",
    "Steam": "蒸汽",
    "The production of secondary elements is going along slowly. It uses a huge amount of primary elements to make even trace amounts of secondaries.\n\t\t\tI'll have to figure out how to improve them.": "次要元素的生产进展缓慢。 它使用大量的主要元素来制造甚至微量的次要元素。\n\t\t\t我必须弄清楚如何改进它们。",
    "Today a few militarymen came for \"inspection\", presumably checking for any anti-militarist things.": "今天有几个士兵来“检查”，想必是检查有没有反军G主义的东西。",
    "Traces of Magma": "岩浆痕迹",
    "Traces of Sand": "沙之痕迹",
    "Traces of Steam": "蒸汽痕迹",
    "Volcano": "火山",
    "Catalysed Water Conversion": "催化水转化",
    "Catalysed Fire Conversion": "催化火转化",
    "Catalysed Earth Conversion": "催化土转化",
    "Catalysed Air Conversion": "催化气转化",
    "Energy Vacuum": "能量真空",
    "Matter Vacuum": "物质真空",
    "No processes produce Energy Vacuum.": "没有进程产生能量真空。",
    "No processes produce Matter Vacuum.": "没有进程产生物质真空。",
    "No processes use Energy Vacuum.": "没有进程使用能量真空。",
    "No processes use Matter Vacuum.": "没有进程使用物质真空。",
    "True Void": "真虚空",
    "Voidal Drain": "虚空汲取",
    "Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "锅炉、火山、粉碎机、虚空汲取、徽章合并\n",
    "Crystalliser, Evaporator, Refrigerator, Emblem Merger\n": "结晶器、蒸发器、冰箱、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Boiler, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、锅炉、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Boiler, Pulverizer, Voidal Drain, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、锅炉、粉碎器、虚空排水管、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Boiler, Voidal Drain, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、锅炉、虚空引流器、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、锅炉、火山、粉碎器、虚空排水管、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、冰箱、徽章合并器\n",
    "Crystalliser, Liquefier, Evaporator, Incinerator, Infuser, Swamp, Emblem Merger\n": "结晶器、液化器、蒸发器、焚化器、注入器、沼泽、徽章合并\n",
    "Crystalliser, Liquefier, Evaporator, Infuser, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、注入器、冰箱、徽章合并器\n",
    "Crystalliser, Liquefier, Evaporator, Refrigerator, Emblem Merger\n": "结晶器、液化器、蒸发器、冰箱、徽章合并\n",
    "Crystalliser, Refrigerator, Emblem Merger\n": "结晶器、冰箱、徽章合并\n",
    "Evaporator, Incinerator, Infuser, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "蒸发器、焚化炉、注入器、锅炉、火山、粉碎机、虚空汲取、徽章合并\n",
    "Incinerator, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "焚烧炉、锅炉、火山、粉碎机、虚空汲取、徽章合并\n",
    "Incinerator, Infuser, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "焚化炉、注入器、锅炉、火山、粉碎机、虚空汲取、徽章融合\n",
    "Liquefier, Evaporator, Incinerator, Infuser, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "液化器、蒸发器、焚化器、注入器、锅炉、火山、粉碎器、虚空汲取、徽章合并\n",
    "Pulverizer, Emblem Merger\n": "粉碎者、徽章合并\n",
    "Refrigerator, Emblem Merger\n": "冰箱、徽章合并\n",
    "Swamp, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "沼泽、锅炉、火山、粉碎者、虚空汲取、徽章合并\n",
    "Swamp, Emblem Merger\n": "沼泽、徽章合并\n",
    "Swamp, Refrigerator, Boiler, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "沼泽、冰箱、锅炉、火山、粉碎机、虚空汲取、徽章合并\n",
    "Swamp, Refrigerator, Pulverizer, Voidal Drain, Emblem Merger\n": "沼泽、冰箱、粉碎机、虚空汲取、徽章合并\n",
    "Swamp, Refrigerator, Voidal Drain, Emblem Merger\n": "沼泽、冰箱、虚空汲取、徽章合并\n",
    "Swamp, Refrigerator, Volcano, Pulverizer, Voidal Drain, Emblem Merger\n": "沼泽、冰箱、火山、粉碎机、虚空汲取、徽章合并\n",
    "Voidal Drain, Emblem Merger\n": "虚空汲取、徽章合并\n",
    "Volcano, Emblem Merger\n": "火山、徽章合并\n",
    "Its pulling force which is strong enough to hold things together without crushing them, improving the efficiency of the secondary conversions\n\t\t\tby reducing loss of elements to the surroundings. It can also forcefully pull large amount of elements out from rifts.": "它的拉力足够强大，可以将物体固定在一起而不会将它们压碎，通过减少元素损失到周围环境来提高次要转换的效率。 它还可以强行从裂缝中拉出大量元素。",
    "I saw one of them leave a small notebook on my desk before leaving. On it was a note that read, \"Hi. I'm an alchemist working undercover as an inspector.\n\t\t\tI'm part of the team trying to defeat the regime with elements. Part of my team detected a large amount of elemental waves coming from your region, so I decided to pay a visit.\n\t\t\tI'm impressed with your work. You've discovered new ways to synthesize elements that we never would've thought of.": "我看到其中一个人在离开之前在我的桌子上留下了一本小笔记本。 上面有一张纸条，上面写着：“嗨。我是一名炼金术士，担任卧底检查员。\n\t\t\t我是试图用元素击败政权的团队的一员。我的团队的一部分发现了 大量的元素波来自你所在的地区，所以我决定去拜访一下。\n\t\t\t你的工作给我留下了深刻的印象。你发现了我们从未想过的合成元素的新方法 的。",
    "I accidentally placed a bunch of matter vacuum next to the four primary elements. It sucked them up and caused them to annihilate\n\t\t\tin a brilliant flash of violet light. The resulting substance started sucking all my primary elements towards it, and also sucked energy from the generator\n\t\t\tpowering the machines, almost knocking me out.": "我不小心在四个主要元素旁边放置了一堆物质真空。 它吸走了他们，并导致他们湮灭\n\t\t\在一道耀眼的紫光中。 由此产生的物质开始将我所有的主要元素吸向它，并从发电机中吸取能量\n\t\t\t为机器提供动力，几乎将我击倒。",
    "After containing the substance and doing limited tests with it, I found that its sucking power was enough to bypass the speed of elemental waves in the pipes and\n\t\t\ttrigger an exponential feedback loop for the primary elements. If I can fit the right amount into the machines, I could increase primary element production and stop having to worry about them.": "在容纳该物质并对其进行有限测试后，我发现它的吸力足以绕过管道中元素波的速度，并\n\t\t\t触发主要元素的指数反馈回路。 如果我能在机器中装入适量的材料，我就可以增加主要元件的产量，而不必再担心它们。",
    "\"I've decided to help you out a bit by letting you know about our latest discovery, which involves synthesizing alkahest, the universal solvent.\n\t\t\tAlkahest is an extremely useful precursor for going beyond the secondary and voidal elements, but unfortunately, synthesizing alkahest \n\t\t\tis quite a cumbersome process, and even subject to change over time. This change occurs ever 3-4 years, and mysteriously, every time it's changed, the city of Cassiopeia,\n\t\t\tthe birthplace of alchemy, is plunged into complete darkness for a day or two. But that's getting off topic.": "\“我决定帮助你一点，让你了解我们的最新发现，其中涉及合成 万能溶剂，通用溶剂。\n\t\t\tAlkahest 是超越次级和虚空的极其有用的前体。 元素，但不幸的是，合成 万能溶剂\n\t\t\是一个相当繁琐的过程，甚至会随着时间的推移而发生变化。这种变化每隔3-4年发生一次，而神秘的是，每次变化，仙后座城， \n\t\t\t炼金术的发源地，有一两天陷入完全的黑暗。但这已经偏离主题了。",
    "\"Anyway, I thought I'd save you some time in discovering it yourself. In the book are some notes on the latest information\n\t\t\tabout building a machine to synthesize and contain alkahest. I'll talk more about myself the next time I'm on duty in this region.": "\“无论如何，我想我可以为你节省一些时间来自己发现它。书中有一些关于最新信息的注释\n\t\t\t关于建造一台合成和含有碱的机器。我会谈论更多 下次我在这个地区执勤时，请介绍一下我自己。",
    "\"Most importantly, don't tell anyone about this. You never know who to trust.\"": "“最重要的是，不要告诉任何人这件事。你永远不知道该相信谁。”",
    "Anticaster": "反施法者",
    "Antitype Annihilation": "原型湮灭",
    "As expected, a couple of militarymen came today again. They didn't find my laboratory, but they nicked a bunch of rations.\n\t\t\tI'm out of food for the next few days.": "果然，今天又来了几个军人。 他们没有找到我的实验室，但他们偷走了一堆口粮。\n\t\t\t接下来的几天我没有食物了。",
    "Back to Basics": "回归本源",
    "Better Vacuum?": "更好的真空？",
    "Blank": "空白的",
    "Caster": "脚轮",
    "Distiller": "蒸馏器",
    "Elementary Expulsion": "初级开除",
    "Failed Infernal Merge": "地狱融合失败",
    "Forward to Vacuum": "前进到真空",
    "Hex Distillation": "六面蒸馏",
    "Hex Drain": "六面汲取",
    "Hex Fluid": "六面流体",
    "Hex Fluid (Info)": "六面流体（信息）",
    "Hex Shells": "六面外壳",
    "Hex Shells (Info)": "六面外壳（信息）",
    "Hexes": "六面体",
    "Hexes (Info)": "六面体（信息）",
    "I notice trace amounts of secondary elements forming around the voidal drain. I wonder if it's possible to extract them to improve the efficiency of the process.": "我注意到在虚空引流管周围形成了微量的次生元素。 我想知道是否可以提取它们以提高过程的效率。",
    "I'll have to install some sort of shield to block the propagation of elemental waves. Meanwhile, though, merging ice and magma did give void, but only a really weak version of it. There was also no mud produced.": "我必须安装某种防护罩来阻止元素波的传播。 但与此同时，冰与岩浆的融合确实产生了虚空，但只是虚空的一个非常弱的版本。 也没有产生泥浆。",
    "I've named the new element an energy vacuum for its ability to suck energy.": "我将这种新元素命名为能量真空，因为它具有吸收能量的能力。",
    "It could be holding the secret that allows for scaling reaction rates. I'm going to call it a matter vacuum for having properties similar to a vacuum.": "它可能掌握着扩大反应速率的秘密。 我将其称为物质真空，因为它具有类似于真空的特性。",
    "It did not work out how I expected it to. I tried merging sand + steam, but all that did was spew elemental waves everywhere, damaging my laboratory.": "它没有按照我的预期进行。 我尝试将沙子和蒸汽合并，但所做的只是向各处喷出元素波，损坏了我的实验室。",
    "Lossless Ice Conversion": "无损冰转换",
    "Lossless Magma Conversion": "无损岩浆转换",
    "Lossless Sand Conversion": "无损沙子转换",
    "Magicia": "魔法师",
    "Maybe it's about time I opened that book to see what's inside... Holy hell, you can infuse emblems together? I have to try this out some time soon...": "也许是时候我打开那本书看看里面有什么了……天啊，你能把徽章融合在一起吗？ 我必须尽快尝试一下......",
    "More inspectors came. They were quiet and didn't nick anything, unlike the last bunch.": "更多的检查员来了。 与最后一群人不同，他们很安静，没有划伤任何东西。",
    "No processes use Hex Fluid.": "没有进程使用 六面汲取。",
    "No processes use Hex Shells.": "没有进程使用 六面外壳。",
    "No, that can't be. Doing so would go directly against the oath that an alchemist has to swear before bearing the official title.\n\t\t\tThe recipes must have worked when they were first discovered. But why don't they work now?": "不，那不可能。 这样做将直接违反炼金术士在获得正式头衔之前必须宣誓的誓言。\n\t\t\t这些配方在第一次被发现时一定是有效的。 但为什么他们现在不工作呢？",
    "Orb Orb Infusion": "宝珠 宝珠灌注",
    "Relation": "关系",
    "Seemingly everything in these texts are outdated in some way, even ones published recently. Surely they can't be leading future alchemists on false trails?": "似乎这些文本中的所有内容都在某种程度上过时了，即使是最近出版的内容也是如此。 他们肯定不会把未来的炼金术士引向错误的道路吧？",
    "Spatial Anomaly x5": "空间异常 x5",
    "Temporal Anomaly x5": "时间异常 x5",
    "This new weak substance might not be as useful as void, but it's pretty neat in its own right.": "这种新的弱物质可能不像虚空那么有用，但它本身就非常简洁。",
    "Void Synthesis": "虚空合成",
    "Void Usage": "无效使用",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'I',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'Ø': 'Ø',
    'v0.2': 'v0.2',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": " ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Water ": "水 ",
    "Fire ": "火 ",
    "Air ": "气 ",
    "Mud ": "泥 ",
    "Ice ": "冰 ",
    "Earth ": "土 ",
    "Steam ": "蒸汽 ",
    "Magma ": "岩浆 ",
    "Emblems ": "纹章 ",
    "Sand ": "沙子 ",
    "Origin ": "起源 ",
    "Affects: ": "影响：",
    "Emblemic Power ": "纹章力量 ",
    "boosting Air gain and cap by x": "将气增益和上限提高 x",
    "boosting Earth gain and cap by x": "将土增益和上限提高 x",
    "boosting Fire gain and cap by x": "将火增益和上限提高 x",
    "boosting Water gain and cap by x": "将水增益和上限提高 x",
    "Merge: ": "合并：",
    "Energy Vacuum ": "能量真空 ",
    "Matter Vacuum ": "物质真空 ",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "",
    "                  ": "",
    "                 ": "",
    "                ": "",
    "               ": "",
    "              ": "",
    "             ": "",
    "            ": "",
    "           ": "",
    "          ": "",
    "         ": "",
    "        ": "",
    "       ": "",
    "      ": "",
    "     ": "",
    "    ": "",
    "   ": "",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    " to secondary element conversion efficiency\n": "到次要元件的转换效率\n",
    " to all secondary element generation speed": " 至所有次要元素生成速度",
    " to Earth, Water, Air, and Fire generation speed and cap\n": " 为土、水、空气和火的生成速度和上限\n",
    " to primary element cap": " 至初级元件上限",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e(\d+)$/,
    /^([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^([\d\.]+)M$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^x([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Reach (.+) undefined to unlock \(You have (.+) undefined\)$/, '达到 $1 个未定义即可解锁（您有 $2 未定义）'],
    [/^\t(.+)\n\t\t\t\t\tSteam\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t蒸汽/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMud\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t泥/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tIce\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t冰/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMagma\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t岩浆/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tSand\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t沙子/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tAir\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t气/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tFire\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t火/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tWater\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t水/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEarth\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tHexes\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土/六面体\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tHex Fluid\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土/六面流体\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tHex Shells\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土/六面外壳\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEnergy Vacuum\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t能量真空/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMatter Vacuum\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t物质真空/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEmblemic Power\/s\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t纹章力量/秒\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tSteam\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t蒸汽\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMud\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t泥\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMagma\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t岩浆\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tIce \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t冰 \(Cat.\)\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMud \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t泥 \(Cat.\)\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tSteam \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t蒸汽 \(Cat.\)\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t\n\t\t\t\t\tSteam \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t\n\t\t\t\t\t蒸汽 \(Cat.\)\n\t\t\t\t\t\($1\/$2\)\n'],
    [/^\t\n\t\t\t\t\tSand \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t\n\t\t\t\t\t沙子 \(Cat.\)\n\t\t\t\t\t\($1\/$2\)\n'],
    [/^\t\n\t\t\t\t\tMud \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t\n\t\t\t\t\t泥 \(Cat.\)\n\t\t\t\t\t\($1\/$2\)\n'],
    [/^\t\n\t\t\t\t\tMagma \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t\n\t\t\t\t\t岩浆 \(Cat.\)\n\t\t\t\t\t\($1\/$2\)\n'],
    [/^\t\n\t\t\t\t\tIce \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t\n\t\t\t\t\t冰 \(Cat.\)\n\t\t\t\t\t\($1\/$2\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMagma \(Cat.\)\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t岩浆 \(Cat.\)\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tSand\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t沙子\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tIce\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t冰\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tAir\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t气\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tFire\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t火\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tWater\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t水\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEarth\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tMud Emblems\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t泥纹章\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tAir Emblems\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t气纹章\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tFire Emblems\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t火纹章\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tWater Emblems\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t水纹章\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^\t(.+)\n\t\t\t\t\tEarth Emblems\n\t\t\t\t\t\((.+)\/(.+)\)\n$/, '\t$1\n\t\t\t\t\t土纹章\n\t\t\t\t\t\($2\/$3\)\n'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
	[/^([\d\.]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+)\/sec$/, '$1\/秒'],
	[/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
	[/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) Hexes\/s \(([\d\.]+)\/([\d\.]+)\)$/, '$1 六面体\/秒 \($2\/$3\)'],
    [/^([\d\.]+) Hex Shells\/s \(([\d\.]+)\/([\d\.]+)\)$/, '$1 六面体外壳\/秒 \($2\/$3\)'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+) Mud$/, '$1 泥'],
    [/^([\d\.]+) Magma$/, '$1 岩浆'],
    [/^([\d\.]+) Steam$/, '$1 蒸汽'],
    [/^([\d\.]+) Sand$/, '$1 沙子'],
    [/^([\d\.]+) Hex Fluid$/, '$1 六面流体'],
    [/^([\d\.]+) Hex Shells$/, '$1 六面外壳'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+) Fire$/, '$1 火'],
    [/^([\d\.,]+) Hexes$/, '$1 六面体'],
    [/^([\d\.,]+) Mud$/, '$1 泥'],
    [/^([\d\.,]+) Air$/, '$1 气'],
    [/^([\d\.,]+) Ice$/, '$1 冰'],
    [/^([\d\.,]+) Magma$/, '$1 岩浆'],
    [/^([\d\.,]+) Steam$/, '$1 蒸汽'],
    [/^([\d\.,]+) Sand$/, '$1 沙子'],
    [/^([\d\.,]+) Water$/, '$1 水'],
    [/^([\d\.,]+) Earth$/, '$1 土'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);